#Installing yfinance

In [1]:
!pip install yfinance

In [2]:
import yfinance as yf

#Setting Dates

In [3]:
import datetime as dt
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta

In [4]:
end = dt.today()
start = dt.today() - relativedelta(years=5)

In [5]:
print(start)
print(end)

2019-10-07 09:03:57.142366
2024-10-07 09:03:57.142283


#SBI Data

In [6]:
data = yf.download('SBIN.NS', start, end)

[*********************100%***********************]  1 of 1 completed


In [7]:
data.head()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2019-10-07  251.500000  253.399994  246.850006  249.100006  234.463974   
2019-10-09  250.100006  262.000000  244.350006  260.950012  245.617722   
2019-10-10  258.000000  258.000000  252.600006  254.149994  239.217255   
2019-10-11  256.200012  261.399994  251.500000  254.550003  239.593750   
2019-10-14  256.950012  259.399994  254.000000  255.449997  240.440857   

              Volume  
Date                  
2019-10-07  39160623  
2019-10-09  60328507  
2019-10-10  37577511  
2019-10-11  43272106  
2019-10-14  28265136

In [8]:
data.shape

(1237, 6)

# Day Closing with Linear Regression

In [9]:
import numpy as np

In [10]:
x = data.iloc[:, :1].values
y = data.iloc[:, 3].values

In [13]:
x

array([[251.5       ],
       [250.1000061 ],
       [258.        ],
       ...,
       [788.        ],
       [789.90002441],
       [792.        ]])

In [14]:
y

array([249.1000061 , 260.95001221, 254.1499939 , ..., 796.95001221,
       794.09997559, 796.65002441])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [16]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()

In [17]:
linreg.fit(X_train,y_train)

LinearRegression()

In [18]:
y_pred = linreg.predict(X_test)

In [19]:
y_pred

array([274.68236656, 153.61311653, 544.4068589 , 481.20345018,
       395.90126347, 315.58750873, 576.73192244, 782.15557538,
       585.96052158, 593.94201274, 617.8864862 , 484.44593096,
       256.17529613, 823.70917716, 631.85409572, 313.59213594,
       414.35846176, 565.0091073 , 523.10627874, 215.8188693 ,
       272.48744432, 436.80640564, 746.28873732, 615.89111341,
       277.72529789, 596.83532764, 187.88365026, 545.90338849,
       517.51925929, 335.24194288, 815.57806959, 535.07851547,
       531.0877699 , 504.15023725, 610.90268144, 370.95910361,
       332.9472459 , 561.96617598, 174.81395241, 171.07262843,
       484.19650937, 422.73902139, 249.83998144, 240.26218596,
       649.06418602, 557.62620363, 159.39970066, 534.57967228,
       473.72080223, 568.00216649, 456.11164346, 408.8711866 ,
       389.41630191, 534.03095694, 333.64563856, 564.7596857 ,
       269.69393459, 757.26328766, 269.74380673, 420.34458013,
       625.26938988, 577.72960883, 193.91965599, 192.32

In [20]:
column_values = ['Actual', 'Predicted']

In [21]:
values = np.array([y_test, y_pred])

In [22]:
import pandas as pd

In [23]:
res = pd.DataFrame(data={'Predicted': y_pred, 'Actual': y_test})

In [24]:
res

Predicted      Actual
0    274.682367  274.950012
1    153.613117  151.949997
2    544.406859  545.849976
3    481.203450  490.600006
4    395.901263  405.049988
..          ...         ...
305  571.494069  578.549988
306  572.791049  569.950012
307  460.252036  454.399994
308  508.440277  512.400024
309  742.497541  748.099976

[310 rows x 2 columns]

In [25]:
res.corr()

Predicted    Actual
Predicted   1.000000  0.998994
Actual      0.998994  1.000000

In [26]:
# Mean Squared Error (MSE)
from sklearn.metrics import mean_squared_error
MSE=mean_squared_error(y_test, y_pred)
print('Mean Squared Error is:', MSE)

Mean Squared Error is: 63.76094812191307


In [27]:
# Root Mean Squared Error (RMSE)
import math
RMSE = math.sqrt(MSE)
print('Root Mean Squared Error is:', RMSE)

Root Mean Squared Error is: 7.985045279891221


In [28]:
val = 23.75
pred = linreg.predict([[val]])
print(pred)

diff = pred-val
if diff>0:
  print('Gain today')
else:
  print('Loss today')


[24.01366]
Gain today
